Concurrent translation of multiple keys
yihong0618/bilingual_book_maker pull request #136
Opened 2023-03-10 08:03 UTC by hleft

This is the simplest case of concurrent translation, no error handling, no resume function, can be used with care, if all goes well, it will be very fast
Or wait for https://github.com/yihong0618/bilingual_book_maker/pull/62

Usage: --max_procs num Note that first -h look at

If this parameter is not used, the program functions unchanged

If it is used, the output is modified because it is no longer outputting the content before and after translation because it is too fast.
Instead, it outputs the file inside the epub currently being processed and the apikey used for the current request (so you can see how fast it is now)

Note that it does not care how many keys you have, if you only have 3 keys, but concurrently 100, there will be problems
I suggest 30 keys, concurrently 5 will be fine

It may output the wrong progress but the result book is correct, I think it should not output the progress bar, but it sometimes outputs... I don't know why.

2023-03-10 09:37 UTC, yihong0618 commented
I will take a look at #112 first maybe tonight

2023-03-10 11:19 UTC, hleft commented
speed test:

wc -w ：151581
wc -c：1201147
16.08s user 0.89s system 0% cpu 1:10:30.73 total
args: --max_procs 2

2023-03-10 13:14 UTC, hleft commented on book_maker/translator/chatgptapi_translator.py
> +        print(openai.api_key)
> don't print the key ....

Okay, this is to see the real speed of sending requests. I don’t know whether to add a number to show the number of requests

2023-03-10 13:23 UTC, yihong0618 commented on book_maker/translator/chatgptapi_translator.py
> +        print(openai.api_key)
or replace the middle of the key to **************

2023-03-10 17:13 UTC, Arborym requested changes

2023-03-18 07:11 UTC, hleft commented
A bit busy right now..

2023-04-01 09:36 UTC, hleft commented
Now a lot of codes have changed, and I am using this function locally and no interest in improving this pr and fix conflicts. I feel that modifying it is not as good as raising a new pr, so I closed it and welcome others to pr

2023-04-01 09:36 UTC, closed without merging